expname: 0494-qvduoduocookies-box
basedir: experiments/onepose
dataset_type: video_onepose
scenes: [0494-qvduoduocookies-box]

render:
  N_samples: 64
  N_rand: 512
  chunk: 2048
  render_feature: True

max_epochs: 30

use_depth_supervision: False

matching:
  keypoints_3d_sampling: random
  keypoints_3d_sampling_max_keep: 8192
  coarse_matching_depth_thresh: 0.02
  coarse_num_3d_keypoints: 1024
  fine_num_3d_keypoints: 1024

backbone2d_use_fpn: True

encode_appearance: False
appearance_emb_dim: 128

n_views_train: 16
n_views_test: 16

train_nerf: True
train_pose: True

backbone2d: cotr
backbone2d_fpn_dim: 192
support_image_selection: coreset
coreset_sampler: FPS
image_core_set_size: 16
image_retrieval_method: netvlad
image_retrieval_method_train: netvlad
image_retrieval_method_test: netvlad
image_retrieval_interval_train: 10
image_retrieval_interval_test: 10

render_loss_weight: 1.0
ref_depth_loss_weight: 1.0

use_scene_coord_memorization: True
ckpt: experiments/onepose/all/default/checkpoints/last.ckpt